<<<<<<< HEAD
custom:
  - https://www.buymeacoffee.com/coteschung
  - https://cotes.gitee.io/alipay-wechat-donation
=======
ko_fi: coteschung
custom: https://sponsor.cotes.page
>>>>>>> 684f32b1f4d74433fccc767095b153fc618db864
