<<<<<<< HEAD
name: 'Continuous Integration'
=======
name: 'CI'
>>>>>>> 684f32b1f4d74433fccc767095b153fc618db864
on:
  push:
    branches-ignore:
      - 'production'
<<<<<<< HEAD
    tags-ignore:
      - '*'
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/ci.yml'
      - '.travis.yml'
      - '.gitignore'
      - 'docs/**'
=======
      - 'docs'
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/ci.yml'
      - '.gitignore'
>>>>>>> 684f32b1f4d74433fccc767095b153fc618db864
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths:
      - '**'

jobs:
<<<<<<< HEAD
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
=======
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [2.7, 3]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
>>>>>>> 684f32b1f4d74433fccc767095b153fc618db864
        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
<<<<<<< HEAD
          ruby-version: 2.7
          bundler-cache: true

      - name: Build Site
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll b

      - name: Test Site
        run: |
          bash tools/test.sh
=======
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Test Site
        run: bash tools/test
>>>>>>> 684f32b1f4d74433fccc767095b153fc618db864
